-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.comments
(
    id bigserial NOT NULL,
    title character varying(500),
    comment_text text,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.comments
    IS 'Table to store comments';

CREATE TABLE IF NOT EXISTS public.replyto
(
    "responseId" bigserial NOT NULL,
    "commentId" integer,
    title character varying(500),
    replytext text,
    PRIMARY KEY ("responseId")
);

COMMENT ON TABLE public.replyto
    IS 'table to store replies of comments';

ALTER TABLE IF EXISTS public.replyto
    ADD FOREIGN KEY ("commentId")
    REFERENCES public.comments (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;